# Generated by Django 2.0 on 2018-03-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
